### ISSUE TITLE
Add this as environment variable

### ISSUE THREAD

**Issue by jgmuchiri** [Lambda-School-Labs/djhelper-fe#15]
https://github.com/Lambda-School-Labs/djhelper-fe/blob/637415f953f5132c86a7b377226d82f3c6eeb7f0/src/actions/action.js#L43

Also, evaluate whether the environment is production or development to determine which URL to use

**Comment by ethyl2** [comment]
Yes, lines 42-43 should be taken out, now that we have our axiosWithAuth function using the environmental variable, I believe. And, yes, we should implement a check for the current environment in the axiosWithAuth function.

**Comment by ethyl2** [comment]
Backend url is now specified using an environmental variable.
