### ISSUE TITLE
Hardcoded URL could be added as environment variable

### ISSUE THREAD

**Issue by jgmuchiri** [Lambda-School-Labs/djhelper-fe#16]
https://github.com/Lambda-School-Labs/djhelper-fe/blob/637415f953f5132c86a7b377226d82f3c6eeb7f0/src/utils/axiosWithAuth.js#L5

**Comment by ethyl2** [comment]
Thank you! Yes, yesterday we added it as an environmental variable (see line 4) as REACT_APP_BACKEND_HOST. We left our code as an OR statement as a fallback until we are sure that all of our team has that variable in their local .env files.
